const key = {
"Sb1": "Bligh Bank Lp.; zeezand",
"Sb2": "Terschellingerbank Lp.; omgewerkt (peri-)glaciaal slibhoudend zeezand (slib <10%)",
"Sb3": "Buitenbanken Lp.; omgewerkt grindhoudend rivierzand",
"Sb4": "Indefatigable Grounds Lp.; omgewerkt glaciaal grind en grindhoudend zand",
"U1": "Urania Formatie Western Mud Hole Lp.;zeer fijn omgewerkt (peri-)glaciaal zand en slib (slib >10%)",
"U2": "Urania Formatie Well Hole Lp.; uiterst fijn tot zeer fijn (slbihoudend) zeezand en slib",
"Na1": "Laagpakket van Schoorl / Zandvoort; duin- en strandzand",
"Na2": "Formatie van Naaldwijk; zeeklei en -zand",
"Na3": "Formatie van Naaldwijk / Formatie van Nieuwkoop; zeeklei en -zand met inschakelingen van veen",
"Na4": "Formatie van Naaldwijk op Formatie van Nieuwkoop; zeeklei op veen",
"Na5": "Formatie van Naaldwijk op Pleistocene formaties; zeeklei en -zand op zand",
"Na6": "Laagpakket van Walcheren; zeeklei en -zand",
"Na7": "Laagpakket van Walcheren / Formatie van Nieuwkoop; zeeklei en -zand met inschakelingen van veen",
"Na8": "Laagpakket van Walcheren op Formatie van Nieuwkoop; zeeklei op veen",
"Na9": "Laagpakket van Walcheren op Formatie van Nieuwkoop op Laagpakket van Schoorl / Zandvoort; zeeklei op veen op duin- en strandzand",
"Na10": "Laagpakket van Walcheren op Laagpakket van Schoorl / Zandvoort; zeeklei op duin- en strandzand",
"Na11": "Laagpakket van Walcheren op Formatie van Nieuwkoop / Formatie van Echteld; zeeklei en -zand op veen met inschakelingen van rivierklei en -zand",
"Na12": "Laagpakket van Walcheren op Formatie van Echteld; zeeklei op rivierzand en -klei",
"Na13": "Laagpakket van Walcheren op Formatie van Nieuwkoop, Hollandveen Lp. op Laagpakket van Wormer; zeeklei op veen op zeeklei en -zand",
"Na14": "Laagpakket van Walcheren op Laagpakket van Wormer; zeeklei en -zand",
"Na15": "Laagpakket van Walcheren op Pleistocene formaties; zeeklei op zand",
"Na16": "Laagpakket van Wormer; zeeklei en -zand",
"Na17": "Laagpakket van Wormer / Formatie van Nieuwkoop; zeeklei en -zand met inschakelingen van veen",
"Ni1": "Formatie van Nieuwkoop; veen",
"Ni2": "Hollandveen Lp. op Formatie van Naaldwijk, Lp. van Wormer; veen op zeeklei en -zand",
"Ni3": "Formatie van Nieuwkoop / Formatie van Echteld; veen met inschakelingen van rivierklei en -zand",
"Ni4": "Formatie van Nieuwkoop op Formatie van Naaldwijk, Laagpakket van Schoorl / Zandvoort; veen op duin- en strandzand",
"Ni5": "Laagpakket van Griendtsveen; veen",
"Ec1": "Formatie van Echteld; rivierklei op rivierzand",
"Ec2": "Formatie van Echteld / Formatie van Nieuwkoop; rivierklei en -zand met inschakelingen van veen",
"Ec3": "Formatie van Echteld / Formatie van Nieuwkoop op Formatie van Naaldwijk; rivierklei en -zand met inschakelingen van veen op zeeklei en -zand",
"Ec4": "Formatie van Echteld / Formatie van Nieuwkoop op Formatie van Boxtel; rivierklei en -zand met inschakelingen van veen op zand",
"Ec5": "Formatie van Echteld op Formatie van Boxtel; rivierklei op zand",
"Ec6": "Formatie van Echteld op Formatie van Kreftenheye; rivierklei op rivierzand en -grind",
"Ec7": "Formatie van Echteld op Formatie van Beegden; rivierklei op rivierzand en -grind",
"Bx1": "Laagpakket van Kootwijk; stuifzand",
"Bx2": "Laagpakket van Singraven; beekzand en -leem",
"Bx3": "Laagpakket van Singraven; veen",
"Bx4": "Laagpakket van Delwijnen; rivierduinzand",
"Bx5": "Laagpakket van Wierden; dekzand",
"Bx6": "Formatie van Boxtel met een dek van het Laagpakket van Wierden; fluvioperiglaciale afzettingen (leem en zand) met een zanddek",
"Bx7": "Laagpakket van Schimmert; leem (löss)",
"Bx8": "Laagpakket van Schimmert op gestuwde afzettingen; zandige leem (löss) op gestuwd zand en -grind",
"Bx9": "Laagpakket van Wierden op Formatie van Boxtel; dekzand op veen",
"Be1": "Laagpakket van Oost-Maarland; rivierklei op rivierzand en -grind",
"Be2": "Formatie van Beegden; rivierklei op rivierzand en -grind",
"Be3": "Formatie van Beegden; rivierzand en -grind",
"Be4": "Formatie van Beegden veelal met een dek van de Formatie van Boxtel, Laagpakket van Wierden; rivierzand en -grind veelal met een zanddek",
"Be5": "Formatie van Beegden met een dek van de Formatie van Boxtel, Laagpakket van Schimmert; rivierzand en -grind met een dek van leem",
"Kr1": "Formatie van Kreftenheye; rivierzand en -grind",
"Kr2": "Laagpakket van Well met een dek van de Formatie van Beegden; rivierzand en -grind met een dun dek van zand en klei",
"Dr1": "Laagpakket van Gieten; grondmorene (zandige en grindige leem, 'keileem')",
"Dr2": "Laagpakket van Gieten met een dek van de Formatie van Boxtel, Laagpakket van Wierden; grondmorene met een zanddek",
"Dr3": "Laagpakket van Gieten op gestuwde afzettingen; grondmorene op gestuwd zand en grind",
"Dr4": "Laagpakket van Gieten en oudere gestuwde afzettingen; grondmorene en oudere gestuwde afzettingen",
"Dr5": "Laagpakket van Schaarsbergen; glaciofluviale afzettingen (grof zand en grind)",
"Dn1": "Formatie van Drachten met een dek van de Fm. van Boxtel, Laagpakket van Wierden; fluvioperiglaciale afzettingen (leem en zand) met een zanddek",
"Ur1": "Laagpakket van Lingsfort; rivierzand en -grind",
"Pe1": "Formatie van Peelo; glaciofluviale afzettingen (grof tot fijn zand) en glaciolacustriene afzettingen (zwak siltige klei, 'potklei')",
"St1": "Formatie van Sterksel met een dek van de Formatie van Boxtel; rivierzand en -grind met een zanddek",
"Sy1": "Formatie van Stramproy met een dek van de Formatie van Boxtel; fijn tot grof zand en leem met een zanddek",
"Wa1": "Formatie van Waalre met een dek van de Formatie van Boxtel; rivierzand en -klei met een zanddek",
"UAP1": "Formatie van Urk, Appelscha en Peize; door zouttektoniek omhooggedrukt rivierzand en -grind",
"G1": "Gestuwde Pleistocene formaties, veelal rivierzand en -grind",
"G2": "Gestuwde Tertiaire formaties, veelal zeeklei en -zand",
"Ki1": "Kiezeloölietformatie Laagpakket van Waubach; rivierzand en -grind",
"Ki2": "Kiezeloölietformatie Laagpakket van Waubach met een dek van de Formatie van Boxtel, Laagpakket van Schimmert; rivierzand en -grind met een dek van leem",
"Oo1": "Formatie van Oosterhout; zeezand",
"Br1": "Formatie van Breda veelal met een dek van de Formatie van Boxtel; strandzand, zeezand en -klei veelal met een dek van leem, zand of hellingafzettingen",
"Ru1": "Rupelformatie Laagpakket van Boom veelal met een dek van de Formatie van Boxtel; zeeklei veelal met een zanddek",
"Ru2": "Rupelformatie Laagpakket van Boom / Bilzen veelal met een dek van de Formatie van Boxtel; strandzand, zeezand en -klei veelal met een dek van leem of hellingafzettingen",
"To1": "Formatie van Tongeren veelal met een dek van de Formatie van Boxtel; zeezand en -klei veelal met een dek van leem of hellingafzettingen",
"Do1": "Formatie van Dongen veelal met een dek van de Formatie van Boxtel; zeezand en -klei veelal met een zanddek",
"Mt1": "Formatie van Maastricht veelal met een dek van de Formatie van Boxtel; kalksteen veelal met een dek van leem of hellingafzettingen",
"Gu1": "Formatie van Gulpen veelal met een dek van de Formatie van Boxtel; kalksteen veelal met een dek van leem of hellingafzettingen",
"Va1": "Formatie van Vaals veelal met een dek van de Formatie van Boxtel; zand(steen) of klei veelal met een dek van leem of hellingafzettingen",
"Ak1": "Formatie van Aken veelal met een dek van de Formatie van Boxtel; zand(steen) en klei veelal met een dek van leem of hellingafzettingen",
"VZK1": "Vlieland Zandsteen en Kleisteen Fm. veelal met een dek van de Formatie van Boxtel; mariene zand- en kleisteen veelal met een zanddek",
"MR1": "Muschelkalk en Röt Fm. veelal met een dek van de Formatie van Boxtel; kalksteen en kleisteen veelal met een zanddek",
"Ep1": "Formatie van Epen, veelal met een dek van de Formatie van Boxtel; schalies en zandsteen, veelal met een dek van leem of hellingafzettingen"
}